name = "template-api"
compatibility_date = "2024-06-03"
send_metrics = false
compatibility_flags = ["nodejs_als"]
node_compat = true
main = "cmd/server/index.ts"
tail_consumers = [{ service = "api-tail" }]
logpush = true

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "xxx"
localConnectionString = "postgres://user:password@localhost:5432/localdb"

[vars]
SERVICE_NAME = "test-worker"
BASELIME_API_KEY = "xxx"

[queues]
consumers = [
    { queue = "log-queue", max_batch_size = 10, max_retries = 10 },
    { queue = "app-queue", max_batch_size = 10, max_retries = 10 },
]
producers = [
    { queue = "log-queue", binding = "LOG_QUEUE" },
    { queue = "app-queue", binding = "APP_QUEUE" },
]

[[r2_buckets]]
bucket_name = "app-bucket"
binding = "APP_BUCKET"
