name = "api"
compatibility_date = "2024-06-03"
send_metrics = false
node_compat = true
main = "cmd/server/index.ts"
tail_consumers = [{ service = "api-tail" }]
logpush = true

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "xxx"
localConnectionString = "postgres://user:password@localhost:5432/localdb"
